name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest

    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
      LIGHTSAIL_USER: ${{ secrets.LIGHTSAIL_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build and push Admin image
        run: |
          docker build --progress=plain -t $DOCKER_USER/admin:latest -f docker/admin.Dockerfile .
          docker push $DOCKER_USER/portfolio-admin:latest

      - name: Build and push Front image
        run: |
          docker build --progress=plain -t $DOCKER_USER/front:latest -f docker/front.Dockerfile .
          docker push $DOCKER_USER/portfolio-front:latest

      - name: Build and push API image
        run: |
          docker build --progress=plain -t $DOCKER_USER/back:latest -f docker/back.Dockerfile .
          docker push $DOCKER_USER/portfolio-back:latest

      - name: SSH into Lightsail and update containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.LIGHTSAIL_HOST }}
          username: ${{ env.LIGHTSAIL_USER }}
          key: ${{ env.SSH_KEY }}
          script: |
            cd portfolio-deploy
            
            docker compose pull front admin back
            docker compose up -d front admin back
            docker compose restart nginx
            
            docker system prune
