name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
      LIGHTSAIL_USER: ${{ secrets.LIGHTSAIL_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build and push Admin image
        run: |
          docker build -t $DOCKER_USER/admin:latest ./apps/admin
          docker push $DOCKER_USER/portfolio-admin:latest

      - name: Build and push Front image
        run: |
          docker build -t $DOCKER_USER/front:latest ./apps/front
          docker push $DOCKER_USER/portfolio-front:latest

      - name: Build and push API image
        run: |
          docker build -t $DOCKER_USER/back:latest ./apps/back
          docker push $DOCKER_USER/portfolio-back:latest

      - name: SSH into Lightsail and update containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.LIGHTSAIL_HOST }}
          username: ${{ env.LIGHTSAIL_USER }}
          key: ${{ env.SSH_KEY }}
          script: |
            docker pull $DOCKER_USER/admin:latest
            docker pull $DOCKER_USER/front:latest
            docker pull $DOCKER_USER/back:latest

            docker stop portfolio-admin || true
            docker rm portfolio-admin || true
            docker stop portfolio-front || true
            docker rm portfolio-front || true
            docker stop portfolio-back || true
            docker rm portfolio-back || true

            cd ~/portfolio-docker

            docker compose up -d admin front back
